export const partners = [
  { name: "Epson", file: "partner-epson.png" },
  { name: "Alto Professional", file: "partner-alto.png" },
  { name: "Shure", file: "partner-shure.png" },
  { name: "Phonic", file: "partner-phonic.png" },
  { name: "Acer", file: "partner-acer.png" },
  { name: "Yamaha", file: "partner-yamaha.png" },
  { name: "Konzert", file: "partner-konzert.jpg" },
  { name: "Hitachi", file: "partner-hitachi.png" },
  { name: "dbx", file: "partner-dbx.png" },
  { name: "MIPRO", file: "partner-mipro.jpg" },
  { name: "Samson", file: "partner-samson.png" },
  { name: "ATEN", file: "partner-aten.jpg" },
  { name: "Audio-Technica", file: "partner-audio-technica.png" },
  { name: "Polk Audio", file: "partner-polk-audio.png" },
  { name: "Soundcraft", file: "partner-soundcraft.png" },
  { name: "Fender", file: "partner-fender.png" },
  { name: "Cerwin-Vega", file: "partner-cerwin-vega.jpg" },
  { name: "P.Audio", file: "partner-p-audio.jpg" },
  { name: "Kevler", file: "partner-kevler.jpg" },
  { name: "Neutrik", file: "partner-neutrik.png" },
  { name: "Wharfedale Pro", file: "partner-wharfedale-pro.jpg" },
  { name: "Strandtz", file: "partner-strandtz.jpg" },
  { name: "RCF", file: "partner-rcf.jpg" },
  { name: "QSC", file: "partner-qsc.jpg" },
  { name: "Peavey", file: "partner-peavey.jpg" },
  { name: "Samsung", file: "partner-samsung.png" },
  { name: "LG", file: "partner-lg.png" },
  { name: "MSI", file: "partner-msi.jpg" },
  { name: "HP", file: "partner-hp.jpg" },
  { name: "Studiomaster", file: "partner-studiomaster.jpg" },
  { name: "Beta Three", file: "partner-beta-three.jpg" },
  { name: "Apple", file: "partner-apple.jpg" },
  { name: "ASUS", file: "partner-asus.jpg" },
] as const;
